name: CI-CD-Demo-Olivierkab

on:

  push:

    branches:

      - main

permissions:

  contents: write   #  REQUIRED for release creation

jobs:

  build_test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build (generate artifact)

      run: |

        mkdir -p dist

        echo "Build artifact generated Olivierkab at $(date)" > dist/app.txt

    - name: Test (always pass)

      run: |

        echo "All tests passed"

    - name: Upload Build Artifact

      uses: actions/upload-artifact@v4

      with:

        name: build-artifact

        path: dist/

  release:

    needs: build_test

    runs-on: ubuntu-latest

    steps:

    - name: Download Build Artifact

      uses: actions/download-artifact@v4

      with:

        name: build-artifact

        path: dist/

    - name: Create Release

      uses: softprops/action-gh-release@v2

      with:

        tag_name: demo-${{ github.run_number }}

        name: Demo Release ${{ github.run_number }}

        files: dist/*

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




